import type { Event } from "./types";

/** Sample data for development — will be replaced by CloudFront JSON fetch. */
export const SAMPLE_EVENTS: Event[] = [
  {
    id: "a1b2c3d4",
    title: "Santa - Tournée",
    description: "Santa présente son album \"Recommence-moi\" dans une tournée exceptionnelle à travers la France.",
    date_start: "2026-03-24",
    date_end: null,
    time: "20:30",
    location: "Zénith de Rouen - Le Grand-Quevilly",
    address: "44 Avenue des Canadiens, 76120 Le Grand-Quevilly",
    category: "musique",
    tags: ["chanson française", "concert", "live"],
    urls: ["https://www.jds.fr/rouen/concerts/chanson-francaise/santa-tournee-544043_A"],
    image_url: "",
    sources: ["jds"],
    classified_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "e5f6g7h8",
    title: "Albumine & Collodion – Rouen en photographies (1850-1920)",
    description: "Exposition de photographies historiques de Rouen, du daguerréotype aux premières cartes postales.",
    date_start: "2026-03-07",
    date_end: "2026-07-31",
    time: "10:00",
    location: "Bibliothèque patrimoniale",
    address: "3 Rue Jacques Villon, 76000 Rouen",
    category: "expositions",
    tags: ["photographie", "patrimoine", "histoire"],
    urls: ["https://openagenda.com/events/albumine-collodion"],
    image_url: "https://cdn.openagenda.com/main/9a4c5dbd028d4c778e3332727db6cab3.base.image.jpg",
    sources: ["openagenda_metropole", "openagenda_bibliotheques"],
    classified_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "i9j0k1l2",
    title: "Foire de Rouen",
    description: "La grande foire annuelle de Rouen au Parc des Expositions, avec manèges, stands et animations pour toute la famille.",
    date_start: "2026-03-27",
    date_end: "2026-04-12",
    time: "",
    location: "Parc Exposition de Rouen",
    address: "46 Av. des Canadiens, 76120 Le Grand-Quevilly",
    category: "famille",
    tags: ["foire", "manèges", "animations"],
    urls: ["https://rouenonest.fr/foire"],
    image_url: "",
    sources: ["rouen_on_est"],
    classified_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "m3n4o5p6",
    title: "Match Rugby - Rouen Normandie Rugby vs Stade Aurillacois",
    description: "Match de Pro D2 au stade Mermoz.",
    date_start: "2026-03-21",
    date_end: null,
    time: "18:00",
    location: "Stade Jean Mermoz",
    address: "Rue Jean Mermoz, 76000 Rouen",
    category: "sport",
    tags: ["rugby", "pro d2", "match"],
    urls: ["https://www.jds.fr/rouen/sport/match-rugby"],
    image_url: "",
    sources: ["jds"],
    classified_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "q7r8s9t0",
    title: "Murder Game - L'enquête de Sherlock Holmes",
    description: "Plongez dans l'univers de Sherlock Holmes et résolvez une enquête grandeur nature dans les rues de Rouen.",
    date_start: "2026-03-22",
    date_end: "2026-04-30",
    time: "14:00",
    location: "Centre-ville de Rouen",
    address: "Rouen",
    category: "spectacles",
    tags: ["jeu", "enquête", "sherlock holmes"],
    urls: ["https://openagenda.com/events/murder-game"],
    image_url: "",
    sources: ["openagenda_rouen"],
    classified_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "u1v2w3x4",
    title: "Atelier Repair Café",
    description: "Venez réparer vos objets du quotidien avec l'aide de bénévoles spécialisés. Petit électroménager, couture, informatique.",
    date_start: "2026-03-21",
    date_end: null,
    time: "14:00",
    location: "Pavillon des Transitions",
    address: "Quai de Boisguilbert, 76000 Rouen",
    category: "famille",
    tags: ["atelier", "réparation", "écologie"],
    urls: ["https://openagenda.com/events/atelier-repair-cafe"],
    image_url: "",
    sources: ["openagenda_rouen"],
    classified_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "y5z6a7b8",
    title: "Rouen Tattoo Festival",
    description: "Le rendez-vous incontournable des amateurs de tatouage en Normandie. Artistes internationaux, concerts et animations.",
    date_start: "2026-04-24",
    date_end: "2026-04-26",
    time: "10:00",
    location: "Parc Exposition de Rouen",
    address: "46 Av. des Canadiens, 76120 Le Grand-Quevilly",
    category: "festival",
    tags: ["tatouage", "festival", "art"],
    urls: ["https://rouenonest.fr/tattoo-festival"],
    image_url: "",
    sources: ["rouen_on_est"],
    classified_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "c9d0e1f2",
    title: "Bonnie Toy - Au creux de mon ventre",
    description: "Spectacle poétique et musical de Bonnie Toy, entre théâtre et performance.",
    date_start: "2026-04-03",
    date_end: null,
    time: "20:00",
    location: "Le 106",
    address: "Allée François Mitterrand, 76100 Rouen",
    category: "spectacles",
    tags: ["spectacle", "performance", "théâtre"],
    urls: ["https://openagenda.com/events/bonnie-toy"],
    image_url: "",
    sources: ["openagenda_metropole"],
    classified_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "g3h4i5j6",
    title: "Atelier Scientifique - Labo Climat",
    description: "Découvrez les enjeux du changement climatique à travers des expériences scientifiques ludiques et participatives.",
    date_start: "2026-03-25",
    date_end: null,
    time: "14:30",
    location: "Bibliothèque des Capucins",
    address: "1 Rue des Capucins, 76000 Rouen",
    category: "ateliers",
    tags: ["atelier", "science", "climat"],
    urls: ["https://openagenda.com/events/labo-climat"],
    image_url: "",
    sources: ["openagenda_bibliotheques"],
    classified_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "k7l8m9n0",
    title: "Soirée Techno au Diff'art",
    description: "Soirée électro avec DJ sets et performances visuelles.",
    date_start: "2026-03-22",
    date_end: null,
    time: "23:00",
    location: "Diff'art",
    address: "67 Rue Bouquet, 76000 Rouen",
    category: "vie-nocturne",
    tags: ["techno", "dj", "soirée"],
    urls: ["https://example.com/techno-diffart"],
    image_url: "",
    sources: ["jds"],
    classified_at: "2026-03-18T12:00:00Z",
  },
];
